### ISSUE TITLE
Remove Anvil

### ISSUE THREAD

**Issue by fabiooshiro** [Calindra/cartesi-rollups-graphql#4]
```
- name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: ${{ env.ANVIL_TAG }}
```
